title: About GameDev QA
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "https://derkozzz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dmitry Meshcheryakov # add your name
author-img: photo_ava.jpg # add your photo
about-author: "Hi! I am a QA specialist in gamedev. More then 10 years in the industry. I work as Head of QA in Kefir Studio with a team of 15 people. The most famous projects I've worked on are: Last Day on Earth, Forge of Glory, Star Wars: The Old Republic" # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: derkozzz # add your Github handle
social-linkedin: dmitriy-meshcheryakov-41a1b110a # add your Linkedin handle
social-email: derko.derko@gmail.com # add your Email address

# Disqus
discus-identifier: https-derkozzz-github-io # add your discus identifier

# Tracker
analytics: UA-162149614-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
